# Generated by Django 5.0.6 on 2024-06-11 07:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hodimlar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('project_size', models.CharField(max_length=200)),
                ('project_speed', models.CharField(max_length=200)),
                ('project_type', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('project_done_percentage', models.CharField(default=0, max_length=20)),
                ('project_start_date', models.DateTimeField(auto_now=True)),
                ('project_deadline', models.DateField()),
                ('project_budget', models.CharField(max_length=30)),
                ('project_status', models.CharField(choices=[('Yangi', 'Yangi'), ('Jarayonda', 'Jarayonda'), ('Tugatilgan', 'Tugatilgan')], default='Yangi', max_length=30)),
                ('project_spent_money', models.CharField(default=0, max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('project_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='hodimlar.blog')),
                ('project_curator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='curator', to=settings.AUTH_USER_MODEL)),
                ('project_department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='department', to='hodimlar.department')),
                ('project_departments', models.ManyToManyField(related_name='departments', to='hodimlar.department')),
                ('project_team', models.ManyToManyField(related_name='team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyihalar.project')),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(max_length=250)),
                ('phase_done_percentage', models.CharField(default=0, max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyihalar.project')),
            ],
        ),
        migrations.CreateModel(
            name='PermittedProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyihalar.project')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, upload_to='')),
                ('url', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(default='url', max_length=150)),
                ('created_at', models.DateField(auto_now=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyihalar.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=250)),
                ('task_done_percentage', models.CharField(default=0, max_length=20)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyihalar.phase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyihalar.project')),
            ],
        ),
    ]
