# Generated by Django 5.0.6 on 2024-06-11 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hodimlar', '0001_initial'),
        ('loyihalar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_level',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_departments',
            field=models.ManyToManyField(to='hodimlar.department'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_team',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
