# Generated by Django 5.0.6 on 2024-06-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0003_alter_project_project_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_level',
            field=models.CharField(max_length=200),
        ),
    ]
