# Generated by Django 5.0.6 on 2024-06-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0004_alter_project_project_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_department',
        ),
    ]
