# Generated by Django 5.0.6 on 2024-06-12 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hodimlar', '0001_initial'),
        ('loyihalar', '0005_remove_project_project_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='department', to='hodimlar.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_level',
            field=models.CharField(choices=[('Past', 'Past'), ("O'rta", "O'rta"), ('Yuqori', 'Yuqori'), ("O'ta yuqori", "O'ta yuqori")], max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_size',
            field=models.CharField(choices=[('Multi', 'Multi'), ('Mono', 'Mono'), ('Mega', 'Mega')], max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_speed',
            field=models.CharField(choices=[("O'rta", "O'rta"), ('Qisqa', 'Qisqa'), ('Uzoq', 'Uzoq')], max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Aralash', 'Aralash'), ('Iqtisodiy', 'Iqtisodiy'), ('Raqamlashtirish', 'Raqamlashtirish'), ('Strategik', 'Strategik'), ('Tashkiliy', 'Tashkiliy'), ('Texnologik', 'Texnologik')], max_length=200),
        ),
    ]
