# Generated by Django 5.0.6 on 2024-06-12 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0006_project_project_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='problems',
            old_name='description',
            new_name='problem',
        ),
        migrations.AddField(
            model_name='problems',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='problems',
            name='status',
            field=models.CharField(choices=[('Yangi', 'Yangi'), ('Ishlanmoqda', 'Ishlanmoqda'), ('Hal qilindi', 'Hal qilindi')], default='Yangi', max_length=30),
        ),
        migrations.AddField(
            model_name='problems',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyihalar.project')),
            ],
        ),
    ]
